# General
base_url = "https://guylewin.com"
default_language = "en"
title = "Guy Lewin's Blog"
description = "Documenting things I found useful."

theme = "anemone"

# Taxonomies
taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
external_links_target_blank = true
highlight_code = true
highlight_theme = "gruvbox-dark"

[slugify]
paths_keep_dates = true

[extra]
author = "Guy Lewin"
favicon = "favicon.ico"
header_nav = [
  { url = "/", name_en = "/blog/" },
  { url = "/about", name_en = "/about/" },
]